In [1]:
import matplotlib.pyplot as plt
import numpy as np
import numpy.random as rnd
import time
import scipy as sp
from autocorr import autocorr
from scipy.ndimage.interpolation import shift



In [75]:
t = np.arange(50)


In [19]:
print(s)

[ 3.38403483  3.88484052  3.06851254  1.14468141  2.73504613  5.08751169
  4.45781813  2.45816646  2.12149287  3.44772338  3.10345636  4.44127889
  3.73850483  3.03888338  2.86687572  4.78405618  3.59287468  2.55720806
  3.54142836  3.3303918   2.81984773  1.10205206  2.29442015  4.84527474
  2.57593623  3.21825156  2.20990735  4.73211815  1.19050582  3.91642872
  3.30497176  1.23250971  3.50305847  1.64311278  4.276923    1.1115823
  2.82648673  3.76848308  2.31549413  3.44179508  3.22052628  3.35423034
  3.99671132  2.93455843  1.37275188  0.53360476  2.56731676  2.28166264
  2.56162969  2.08702102]


In [5]:
print(t*shift(t,1,cval=0))

[ 0  0  2  6 12 20 30 42 56 72]


In [67]:
s = rnd.normal(3, 1, 50)


In [68]:
autocorr(t,3)

(array([ 1.        , -0.09696258, -0.04966897, -0.22880612]),
 0.24912467079930134)

In [69]:
autocorr(s,5)

(array([ 1.        , -0.09696258, -0.04966897, -0.22880612,  0.01587898,
        -0.05031074]), 0.18026115320535641)

In [70]:
autocorr(s,7)

(array([ 1.        , -0.09696258, -0.04966897, -0.22880612,  0.01587898,
        -0.05031074,  0.02755677, -0.10983597]), 0.015702751060553188)

In [71]:
autocorr(s,10)

(array([ 1.        , -0.09696258, -0.04966897, -0.22880612,  0.01587898,
        -0.05031074,  0.02755677, -0.10983597,  0.12037626,  0.17517545,
        -0.03914282]), 0.5285205197126196)

In [72]:
autocorr(s,15)

(array([ 1.        , -0.09696258, -0.04966897, -0.22880612,  0.01587898,
        -0.05031074,  0.02755677, -0.10983597,  0.12037626,  0.17517545,
        -0.03914282, -0.14815036, -0.30465444,  0.17171953,  0.05639841,
         0.17827929]), 0.43570537081585514)

In [73]:
autocorr(s,20)

(array([  1.00000000e+00,  -9.69625761e-02,  -4.96689665e-02,
         -2.28806122e-01,   1.58789845e-02,  -5.03107433e-02,
          2.75567655e-02,  -1.09835967e-01,   1.20376256e-01,
          1.75175449e-01,  -3.91428216e-02,  -1.48150361e-01,
         -3.04654439e-01,   1.71719530e-01,   5.63984092e-02,
          1.78279287e-01,  -2.15634849e-01,   1.12040080e-01,
         -6.89530692e-02,  -6.74635500e-04,  -3.19709233e-01]),
 -0.55015804151063374)

In [74]:
autocorr(s,25)

(array([  1.00000000e+00,  -9.69625761e-02,  -4.96689665e-02,
         -2.28806122e-01,   1.58789845e-02,  -5.03107433e-02,
          2.75567655e-02,  -1.09835967e-01,   1.20376256e-01,
          1.75175449e-01,  -3.91428216e-02,  -1.48150361e-01,
         -3.04654439e-01,   1.71719530e-01,   5.63984092e-02,
          1.78279287e-01,  -2.15634849e-01,   1.12040080e-01,
         -6.89530692e-02,  -6.74635500e-04,  -3.19709233e-01,
         -1.54765410e-01,   7.98776852e-03,   2.91175143e-01,
          3.66867829e-02,  -8.69485677e-02]), -0.36188660764355829)

In [49]:
tst = autocorr(t,5)
print(tst)

(array([ 1.        ,  0.77777778,  0.51515152,  0.21212121, -0.13131313,
       -0.51515152]), 2.7171717171717171)


In [12]:
np.sum(tst[0])

1.8585858585858577

In [15]:
randBinList = lambda n: [rnd.randint(2) for b in range(1,n+1)]


In [16]:
qq = randBinList(100)