In [2]:
import matplotlib.pyplot as plt
import numpy as np
import numpy.random as rnd
import time
import scipy as sp
from autocorr import autocorr
from scipy.ndimage.interpolation import shift



In [3]:
s = rnd.normal(3, 1, 50)


In [4]:
t = np.arange(10)


In [5]:
print(s)

[ 4.21571983  2.56894565  2.96847325  2.4107339   3.54569488  4.32021113
  2.65146014  1.67853026  2.57505354  2.15550712  3.17554763  2.27675338
  4.3581525   1.24730145  2.37072696  4.35140059  1.99196638  2.13766517
  2.16594466  3.96774097  4.85363209  3.70094987  1.28704327  3.39819819
  1.04501504  1.05635017  1.00036043  2.26271343  4.34477867  1.67813833
  3.59688191  3.16627091  1.60934558  3.14823735  2.37771181  2.5153577
  2.22546763  4.2534798   4.13193928  1.7174238   2.94926811  2.52474155
  2.91820234  3.36215297  2.95371815  4.82998406  4.93071644  2.66468086
  2.6701927   2.86182615]


In [6]:
print(t*shift(t,1,cval=0))

[ 0  0  2  6 12 20 30 42 56 72]


In [7]:
autocorr(s,10)

(array([ 1.        ,  0.07508216, -0.07165498, -0.02066724, -0.13114999,
         0.0024939 , -0.2478722 ,  0.08576455,  0.22951967,  0.06151663,
         0.11333015]), 1.1665089194368259)

In [11]:
randBinList = lambda n: [rnd.randint(2) for b in range(1,n+1)]


In [13]:
qq = randBinList(100)

In [14]:
autocorr(qq,10)

(array([ 1.        ,  0.17137764,  0.0608325 , -0.09324555, -0.1875917 ,
        -0.07331354,  0.02168527,  0.03267113, -0.10877394, -0.20935407,
        -0.04539594]), 1.1415904852848111)

In [17]:
qq[0:]

[0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1]