In [41]:
#notebook used to test bootstrapping functions in bootstrap.py, specifically bs and bs_blocks

In [39]:
import numpy as np
from bootstrap import bs_resample
from bootstrap import bs_mean
import time

In [19]:
B = np.arange(10)
print(B)
qq = np.std(B)
print(qq)

[0 1 2 3 4 5 6 7 8 9]
2.87228132327


In [13]:
np.empty((10,))

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
nn = len(B)
print(nn)
indices = np.floor(nn * rnd.random_sample((10,))).astype(int)
print(indices)
print(B[indices])

#Vn = np.array(B[indices])
#print(Vn)


10


NameError: name 'rnd' is not defined

In [ ]:
nn = len(B)
print(B)
niter = 100
means = np.zeros([100,])

for i in np.arange(niter):
    means[i] = np.mean(bs_resample(B, 100))
    print(means)
    time.sleep(2)

[0 1 2 3 4 5 6 7 8 9]
10
[0 3 1 3 0 4 3 9 5 4 2 9 6 2 8 6 7 4 7 9 0 6 0 5 0 8 3 1 6 0 3 1 2 4 3 1 6
 9 0 8 8 2 8 9 4 2 8 5 5 0 2 3 8 6 1 8 8 5 2 1 8 9 3 5 9 5 2 6 1 8 5 9 7 3
 3 1 5 6 9 1 1 1 2 4 9 4 0 2 0 5 3 0 1 2 3 7 2 4 3 1]
[0 3 1 3 0 4 3 9 5 4 2 9 6 2 8 6 7 4 7 9 0 6 0 5 0 8 3 1 6 0 3 1 2 4 3 1 6
 9 0 8 8 2 8 9 4 2 8 5 5 0 2 3 8 6 1 8 8 5 2 1 8 9 3 5 9 5 2 6 1 8 5 9 7 3
 3 1 5 6 9 1 1 1 2 4 9 4 0 2 0 5 3 0 1 2 3 7 2 4 3 1]
[ 4.12  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.

In [29]:
qq = [1, 2, 3]
qq.append(4)
print(qq)

[1, 2, 3, 4]


In [4]:
A = np.arange(0,1000).reshape(10,10,10)
print(A)

[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]
  [ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 223 224 225 2

In [5]:
B = A + 13

In [6]:
numpy.apply_along_axis(mean)

NameError: name 'numpy' is not defined

# 

In [7]:
np.average([0, 1, 2, 3, 4,6])

2.6666666666666665

In [8]:
np.floor(.1)

0.0

In [9]:
floor(.9)

NameError: name 'floor' is not defined

In [11]:
np.random.random_sample()

0.6412374105118849