In [2]:
#Updating previous MATLAB script to work in Python
#Given meiyu_clean.nc and meiyu_2_clean.nc, finds mean rainband frequency and intensity for different time periods
#and also their product f*q as a proxy for actual rainfall amounts.
#Idea is to help show a causality of rainfall amounts (frequency change, or intensity?)

#meiyu_clean.nc contains every rainband event categorized as primary, and meiyu_2_clean includes all secondary events.

import numpy as np
import time
import os
import netCDF4 as nc
import datetime

In [3]:
#Access NetCDF files (currently hosted in Ferret directory)
RDA_path_1 = "/Users/Siwen/Desktop/ferret/bin/meiyu_clean.nc"
RDA_path_2 = "/Users/Siwen/Desktop/ferret/bin/meiyu_2_clean.nc"
RDA_1 = nc.Dataset(RDA_path_1, 'r')
RDA_2 = nc.Dataset(RDA_path_2, 'r')

In [4]:
#load data from NetCDF files to notebook
lat_1_all =  RDA_1.variables['lat_115'][:]
lat_2_all =  RDA_2.variables['lat_115'][:]
intensity_1_all = RDA_1.variables['intensity'][:] 
intensity_2_all = RDA_2.variables['intensity'][:]

In [5]:
#Assign a calendar date to each time point
startday = datetime.datetime(1951,1,1)
date_list = np.array([datetime.timedelta(days=x) + startday for x in range(0, 20819)])

In [6]:
#Define empty variables reshaped with axis 0 as day of year and axis 1 as year.
lat_1 = np.zeros([365,57])
lat_2 = np.zeros([365,57])
intensity_1 = np.zeros([365,57])
intensity_2 = np.zeros([365,57])

In [82]:
lat_1_all[:20]

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,  27.00996308,  24.21148993,  24.83078497,
        24.77758962,          nan,          nan,          nan,
                nan,          nan,          nan,          nan])

In [89]:
#interestinng unexpected behavior - list(mymap) turns mymap into actual array, but:
#needs to then be converted into np.array, otherwise it chooses either the first or second
#array element based on whether true or false (as opposed to including an element if
#corresponding bool array element is true)!

for i, date in enumerate(date_list[0:365]):
    dd = date.day
    mm = date.month
    mymap = map(lambda date: (date.day == dd) & (date.month == mm), date_list)
    extract = np.array(list(mymap))
    
    lat_1[i,:] = lat_1_all[extract]
    lat_2[i,:] = lat_2_all[extract]
    intensity_1[i,:] = intensity_1_all[extract]
    intensity_2[i,:] = intensity_2_all[extract]

In [90]:
lat_1[100,:]

array([         nan,          nan,  26.46931363,          nan,
                nan,          nan,          nan,  26.664608  ,
        29.40493232,  29.92150069,  25.50032813,  28.43809677,
                nan,  26.62257173,          nan,  28.08974375,
                nan,  24.85880001,          nan,  25.51526638,
                nan,          nan,          nan,          nan,
        26.35480823,          nan,  26.00256665,          nan,
                nan,  26.83154677,  26.09067498,          nan,
        27.58264235,          nan,          nan,  27.38576637,
        28.37376306,  27.47706692,  28.8770144 ,          nan,
        31.97353458,  22.736046  ,  26.6333082 ,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
        25.8300431 ,          nan,  29.22992606,  29.86165066,          nan])

In [9]:
tst[:100]

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
        1.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  1.,  0.,  0.,  1.,  0.])

In [7]:
lat_1[:100]

array([         nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,  27.00996308,  24.21148993,  24.83078497,
        24.77758962,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
        24.56930006,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,  27.63225421,  26.36993152,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,  30.62293474,  28.7239144 ,          nan,
                nan,  25.88566972,          nan,          nan,
                nan,          nan,          nan,  26.67

In [61]:
tst = np.array(date_list)
type(tst)
tst[0]

datetime.datetime(1951, 1, 1, 0, 0)

In [84]:
date_list = np.array([datetime.timedelta(days=x) + startday for x in range(0, 20819)])

In [85]:
mymap = map(lambda date: (date.day == 3) & (date.month == 1), date_list)
test1 = list(mymap)
test2 = np.array(test1)
test3 = np.array(list(mymap))

In [87]:
print(test1[:10])
print(test2[:10])
print(test3[:10])

[False, False, True, False, False, False, False, False, False, False]
[False False  True False False False False False False False]
[]


In [88]:
print(date_list[test1][:10])
time.sleep(3)
print(date_list[test2][:10])
time.sleep(3)
print(date_list[test3][:10])
time.sleep(3)

//anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: FutureWarning: in the future, boolean array-likes will be handled as a boolean array index
  if __name__ == '__main__':


[datetime.datetime(1951, 1, 1, 0, 0) datetime.datetime(1951, 1, 1, 0, 0)
 datetime.datetime(1951, 1, 2, 0, 0) datetime.datetime(1951, 1, 1, 0, 0)
 datetime.datetime(1951, 1, 1, 0, 0) datetime.datetime(1951, 1, 1, 0, 0)
 datetime.datetime(1951, 1, 1, 0, 0) datetime.datetime(1951, 1, 1, 0, 0)
 datetime.datetime(1951, 1, 1, 0, 0) datetime.datetime(1951, 1, 1, 0, 0)]
[datetime.datetime(1951, 1, 3, 0, 0) datetime.datetime(1952, 1, 3, 0, 0)
 datetime.datetime(1953, 1, 3, 0, 0) datetime.datetime(1954, 1, 3, 0, 0)
 datetime.datetime(1955, 1, 3, 0, 0) datetime.datetime(1956, 1, 3, 0, 0)
 datetime.datetime(1957, 1, 3, 0, 0) datetime.datetime(1958, 1, 3, 0, 0)
 datetime.datetime(1959, 1, 3, 0, 0) datetime.datetime(1960, 1, 3, 0, 0)]


IndexError: arrays used as indices must be of integer (or boolean) type

In [65]:
date_list[test2][:5]

IndexError: arrays used as indices must be of integer (or boolean) type